require: rubocop-rspec

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  UseCache: true
  CacheRootDirectory: tmp/rubocop_cache_rails_dir
  MaxFilesInCache: 4000
  Exclude:
    - db/schema.rb
    - features/step_definitions/web_steps.rb
    - features/support/selectors.rb
    - lib/tasks/cucumber.rake

#################### Style ###########################

Style/CommentAnnotation:
  Keywords:
    - TODO-SNAPCON
    - TODO
    - OPTIMIZE
    - HACK
    - REVIEW

Layout/EndOfLine:
  EnforcedStyle: lf

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - features/step_definitions/*

##################### Metrics ##################################

##################### Rails ##################################

Rails:
  Enabled: true

##################### RSpec ##################################

FactoryBot/AttributeDefinedStatically:
  Enabled: true

RSpec/DescribeClass:
  Exclude:
    - "spec/views/**/*"
    - "spec/ability/*"

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
