default: &default
  adapter: 'postgresql'
  encoding: 'unicode'
  host: <%= ENV.fetch('OSEM_DB_HOST', 'database') %>
  port: <%= ENV.fetch('OSEM_DB_PORT', '5432') %>
  username: <%= ENV.fetch('OSEM_DB_USER', ENV.fetch('USER', 'postgres')) %>
  password: <%= ENV.fetch('OSEM_DB_PASSWORD', 'mysecretpassword') %>
  database: <%= ENV.fetch('OSEM_DB_NAME', 'postgres') %>
  pool: 30
  timeout: 60000

development:
  <<: *default
  host: localhost
  # username: <%= ENV['OSEM_DB_USER'] || 'postgres' %>
  database: osem_development

test:
  <<: *default
  host: localhost
  database: osem_test

production:
  <<: *default
